services:

  # =============================================
  # Servicio de traducción (Spanish <-> English)
  # =============================================
  spa_eng:
    build: ./translator
    container_name: translator_spa_eng
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "9001:9001"
    command: >
      python ws_translator_server.py
      --port 9001
      --speech-key 5ae052154f2b4437a2bd13e2a8b1e1fc
      --speech-region eastus
      --translator-key eadeeea0de1b4f718ac400db2023d4ad
      --translator-region eastus
      --src-locale es-ES
      --tgt-lang en
      --tts-voice en-US-JennyNeural
      --name SPA-ENG

  # =============================================
  # Servicio de traducción (English <-> Spanish)
  # =============================================
  eng_spa:
    build: ./translator
    container_name: translator_eng_spa
    network_mode: host
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "9002:9002"
    command: >
      python ws_translator_server.py
      --port 9002
      --speech-key 5ae052154f2b4437a2bd13e2a8b1e1fc
      --speech-region eastus
      --translator-key eadeeea0de1b4f718ac400db2023d4ad
      --translator-region eastus
      --src-locale en-US
      --tgt-lang es
      --tts-voice es-ES-ElviraNeural
      --name ENG-SPA